### ISSUE TITLE
[Feature request] Generate and verify signatures for files other than the `pipeline.yml` file

### ISSUE THREAD

**Issue by DilumAluthge** [staticfloat/cryptic-buildkite-plugin#4]
It is really cool that Buildkite will refuse to run if the `pipeline.yml` file has been changed. E.g. https://buildkite.com/julialang/julia-coverage-linux64/builds/113

However, the `pipeline.yml` files aren't the only sensitive files. For example, for the `coverage-linux64` pipeline, the [`upload_coverage.jl`](https://github.com/JuliaLang/julia/blob/dpa/coverage-serial/.buildkite/coverage-linux64/upload_coverage.jl) file has access to the secret environment variables (`COVERALLS_TOKEN` and `CODECOV_TOKEN`).

So, it would be great if Buildkite would also refuse to run if e.g. the `upload_coverage.jl` file has been changed.

Is there a way I can use the features of this plugin to accomplish this? Essentially, I would want to do the same thing that you are already doing for the `pipeline.yml` file, namely I'd want to generate a signature for the `upload_coverage.jl` file, and then at the beginning of every Buildkite job, we'd check the signature, and Buildkite would refuse to continue if the signature for the `upload_coverage.jl` fails to verify.

**Comment by staticfloat** [comment]
Yes, you list files as other [`inputs` in the launching pipeline](https://github.com/staticfloat/cryptic-buildkite-plugin/blob/main/plugin.yml#L22-L24).  Example:

```yaml
steps:
  # In the WebUI, the `cryptic` launch job _must_ be the first job to run
  - label: ":rocket: launch pipelines"
    plugins:
      - staticfloat/cryptic#408371967b2c4787dd893f4b1b74d11e7ce8f129:
          # Our list of pipelines that should be launched (but don't require a signature)
          # These pipelines can be modified by any contributor and CI will still run.
          # Build secrets will not be available in these pipelines (or their children)
          unsigned_pipelines:
            - .buildkite/pipeline.yml
          signed_pipelines:
            - pipeline: .buildkite/secure_pipeline.yml
              signature_file: .buildkite/secure_pipeline.yml.signature
              inputs:
                  - .buildkite/pipelines/muck_with_s3_buckets.sh
                  - .buildkite/secrets/keys/*.key
                  - .buildkite/secrets/lib/**/*.sh
```
